kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "sample-pipeline"
spec:
  source:
    contextDir: .
    git: 
      uri: https://github.com/garywong-bc/ose-jenkins.git
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: ./Jenkinsfile
      type: JenkinsPipeline
