apiVersion: v1
kind: BuildConfig
metadata:
  name: ootb-jenkins-build
spec:
  source:
    contextDir: ./ootb
    git:
      uri: https://github.com/garywong-bc/ose-jenkins.git
    type: Git
  strategy:                     
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins:latest
        namespace: openshift
    type: Source
  output:                       
    to:
      kind: ImageStreamTag
      name: ootb-jenkins:latest
      namespace: b7cg3n-tools
